use_frameworks!

abstract_target 'ScreenUI' do
  pod 'ScreenUI/Beta', :path => '../'

  target 'ScreenUI_UIKit' do
    platform :ios, '9.0'
    target 'ScreenUI_Tests' do
      inherit! :search_paths

    end
  end

  target 'ScreenUI_AppKit' do
    platform :osx, '10.15'
  end

  target 'ScreenUI_SwiftUI' do
    platform :ios, '14.0'
  end

end
